---
title: "EAAFP interactive map development page"
author: "YCChan"
date: "9/15/2020"
output: html_document

knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})

---
This site is for development purpose.

Counts of > 0.25% of the EAAF population of a species is displayed.

Template for submitting your count data can be downloaded here]( https://github.com/chanyingchi/EAAFPmap.develop/raw/master/count.data.submit.template.xlsx)



Bar-tailed Godwit distribution map

```{r include=FALSE}
source('C:/Users/chan/work/Company/EAAFP species dist map/EAAFP map app/server.R')
datapath<-('C:/Users/chan/work/Company/EAAFP species dist map/species dist data/')
 d.in<-
      read_excel(paste(datapath,'d.btg.all.input.xlsx',sep=''),col_types=c(rep( "guess",3),'text',rep( "guess",8)))
    d.in$subsp[d.in$subsp=='NA']<-NA
    circle.size=5
    d.in$circle.size<-(1.5+circle.size/10)+(log10(1+(d.in$max.count/min(d.in$max.count))*5)*(1+circle.size/8))
m<-make.map(d.in)

```

```{r echo=FALSE, fig.height = 7}
m
```


Bar-tailed Godwit data:

```{r echo=FALSE,layout="l-body-outset"}
library(DT)
d.in<-d.in[order(d.in$lat),]
datatable(d.in[,c(1:4,8:12)])
```





Far Eastern curlew distribution map:

```{r include=FALSE}
source('C:/Users/chan/work/Company/EAAFP species dist map/EAAFP map app/server.R')
datapath<-('C:/Users/chan/work/Company/EAAFP species dist map/species dist data/')
 d.fec<-
      read_excel(paste(datapath,'d.fec.all.input.xlsx',sep=''),col_types=c(rep( "guess",3),'text',rep( "guess",8)))
 d.in<-d.fec
    d.in$subsp[d.in$subsp=='NA']<-NA
    circle.size=5
    d.in$circle.size<-(1.5+circle.size/10)+(log10(1+(d.in$max.count/min(d.in$max.count))*5)*(1+circle.size/8))
m<-make.map(d.in)

```

```{r echo=FALSE, fig.height = 7}
m
```

Far Eastern Curlew data:

```{r echo=FALSE,layout="l-body-outset"}
library(DT)
d.fec<-d.fec[order(d.fec$lat),]
datatable(d.fec[,c(1:4,8:12)])
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
